name: Python CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  buildDependencies:
    name: Build Dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.0-alpha.7"

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4

      - name: Cache Poetry Dependencies
        id: poetry-cache
        uses: actions/cache@v3
        with:
          path: /home/runner/work/<path>/example-app/.venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install Project Dependencies
        run: |
          poetry install --no-root

  staticCodeTests:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    needs: buildDependencies
    defaults:
      run:
        working-directory: ./example-app
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.0-alpha.7"

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4

      - name: Restore Cached Dependencies
        id: restore-cache
        uses: actions/cache@v3
        with:
          path: /home/runner/work/<path>/example-app/.venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Lint Code
        run: |
          poetry run task lint

      - name: Run Code Formatter
        run: |
          poetry run task formatter

      - name: Run Security Checks
        run: |
          poetry run task security

  unitTests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: [buildDependencies, staticCodeTests]
    defaults:
      run:
        working-directory: ./example-app
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.0-alpha.7"

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4

      - name: Restore Cached Dependencies
        id: restore-cache
        uses: actions/cache@v3
        with:
          path: /home/runner/work/<path>/example-app/.venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Run Unit Tests
        run: |
          poetry run task test
