# Workflow do instalacji zależności, lintowania, formatowania i testowania kodu
name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  dependencyInstallJob:
    name: Install Dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"


      - name: Cache Poetry Dependencies
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: /home/runner/work/<path>/example-app/.venv
          key: ${{ runner.os }}-venv

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4

      - name: Install dependencies
        run: |
          poetry install --no-root

  lintJob:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: dependencyInstallJob
    defaults:
      run:
        working-directory: ./example-app
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run linter with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  formatJob:
    name: Format Code
    runs-on: ubuntu-latest
    needs: dependencyInstallJob
    defaults:
      run:
        working-directory: ./example-app
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run code formatter
        run: |
          poetry run task formatter

  testsJob:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [lintJob, formatJob]  # Czeka na zakończenie lintowania i formatowania
    defaults:
      run:
        working-directory: ./example-app
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run tests with pytest
        run: |
          poetry run pytest
